# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVaultNameModification():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_vaultNameModification(self):
    self.driver.get("https://localhost/")
    self.driver.set_window_size(1680, 1025)
    self.driver.find_element(By.LINK_TEXT, "Vaults").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) .btn-warning").click()
    self.driver.find_element(By.ID, "editVaultName").click()
    self.driver.find_element(By.ID, "editVaultName").send_keys("Vault Name Changed")
    self.driver.find_element(By.CSS_SELECTOR, "#editVaultForm > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(1)").text == "Vault Name Changed"
  
