# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVaultUsernameModification():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_vaultUsernameModification(self):
    self.driver.get("https://localhost/")
    self.driver.set_window_size(1680, 1025)
    self.driver.find_element(By.LINK_TEXT, "Vaults").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".edit-password-btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".edit-password-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "editUsername").click()
    self.driver.find_element(By.ID, "editUsername").send_keys("Changed")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1)").text == "Changed"
  
